version: "3.8"  # Specify Docker Compose file format version

services:
  graphdb:
    image: ontotext/graphdb:10.7.6
    container_name: graphdb
    ports:
      - "7200:7200"  # GraphDB Workbench and REST API
      - "7300:7300"  # GraphDB Triplestore Protocol (TSP)
    volumes:
      - graphdb_data:/opt/graphdb/home/data    # Persistent volume
      - ./docker-import:/opt/graphdb/import    # Local import directory
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7200"]  # Optional: add health check
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  graphdb_data:
